### ISSUE TITLE
What paths are allowed?

### ISSUE THREAD

**Issue by jplaisted** [domenic/import-maps#10]
What is allowed in `path_prefix` and a package's `path`? Can it be another domain to load JS hosted elsewhere? Can a scope specify a root path or another domain so as to bypass the implicit URL composition? This seems important to make it clear two scopes can reference the same package (e.g. scope A and scope B can both refer to Cv2 via the same URL). I read through the spec and I initially thought that due to the implicit URL composition this would be impossible, but I asked @shicks his thoughts and he had a looser interpretation of what was allowed in those fields. Might be best to be a little more explicit here even in this early draft. Even if it is along the lines of "We're not exactly sure what should be allowed in these fields, but one could imagine using another domain to reference externally hosted code. See #10.".

**Comment by justinfagnani** [comment]
It's definitely intended for `path_prefix`, `path`, and top-level scope keys to be URLs.

**Comment by jplaisted** [comment]
I didn't even think about scope keys being URLs. But I realize now it makes sense, only way to scope external JS.

I think that should be explicitly stated and/or examples expanded that these fields can be URLs or path pieces. 

In this example from the doc it isn't clear if the scope name is the package name or the path. e.g. what if we needed to scope lodash instead? What would the key be (lodash or lodash-es)? I now believe lodash-es is the correct answer.

```
{
  "path_prefix": "/node_modules",
  "packages": {
    "redux": { "main": "lib/index.js" },
    "html-to-text": { "main": "index.js" },
    "lodash": { "path": "lodash-es", "main": "lodash.js" }
  },
  "scopes": {
    "html-to-text": {
      "path_prefix": "node_modules",
      "packages": {
        "lodash": { "path": "lodash-es", "main": "lodash.js" }
      }
    }
  }
}
```

**Comment by justinfagnani** [comment]
This is more clear in the resolution algorithm, and should be clarified in the schema, but scope keys are path fragments. To resolve a name you look up the correct scope by taking the referer URL and recursively removing matching scope keys from the start of it until there are no more matches.

This not only allows you to define a mapping for another domain, but to define sub-scopes within that domain if necessary.

@domenic I think we can expand on this section to clarify: https://github.com/domenic/package-name-maps#the-package-name-map-format

**Comment by domenic** [comment]
Agreed, the fact that these are URLs needs to be clarified. Maybe we should also have a dedicated example using external URLs.

**Comment by domenic** [comment]
Since the proposal has changed a lot, I have opened a new issue to track this sort of question in the newest iteration: https://github.com/domenic/import-maps/issues/63. I'll close this one and roll it into there.
