### ISSUE TITLE
Matching specificity and performance

### ISSUE THREAD

**Issue by guybedford** [domenic/import-maps#39]
Currently it seems like the matching in the reference implementation is done sequentially. I do have some concerns here from both a specificity and performance perspective as with hundreds or thousands of packages this could incur overhead for each package resolution (~O(rn^2) where n is the number of packages and r is the number of specifiers for a package - 500 packages loaded means 500 lookups against 500 sequential items, where a given package might be itself imported 10s of times giving say 2.5 millions iteration checks just for package names before looking into scopes).

Specificity-based matching which could be preferable for cases like:

```
{
  packages: {
    "jquery": { "main": "index.js" },
    "jquery/x": { "main": "subpackage-main.js" }
  }
}
```

where one might want subpackages to work out naturally, without having to construct some type of special scope precedence trick to get the right matching.

Typically I use dictionary lookups here, specifying these matches in terms of specificity (longest match wins), and then walk down the path segments with dictionary lookups.

So to check a specifier `a/b/c` I would first check `a/b/c` in the dictionary lookup, then `a/b` in a dictionary lookup, finally followed by `a`.

This type of matching process discussed could apply equally to scopes and package names.

**Comment by justinfagnani** [comment]
The reference implementation is not optimized for speed, but for ease of translating to and from spec text. I assume that real implementations would utilize caching and lookup tables.

As for the sequential matching, I think that's easier to understand semantics, but defer to @domenic. With caching, it doesn't have to be an n^2 cost. Also, package names aren't currently paths and don't rely on the path-segment-prefix operation, so splitting on `/` might not make sense. We should clarify this for sure.

**Comment by domenic** [comment]
In the past (e.g. with the module script loading algorithm itself) we've found that implementations really appreciate it when there's something they can more directly translate from spec text into C++, without having to apply their own optimizations. That said, we of course want the spec text/reference implementation to be readable and followable.

So on balance, if there's an alternate (faster-if-naively-implemented) algorithm that is still readable, I'd be open to swapping that out. Probably we should wait until we have high test coverage though, so that we can be more sure we're not changing anything unintentionally.

**Comment by guybedford** [comment]
I think it's clear that the most specific match should win, and that the most specific match will always be the longest match for this matching algorithm. Similarly for scopes.

The approach outlined in https://github.com/domenic/import-maps/issues/73#issuecomment-439327758 seems to be independent of how exact precedence is determined, so I think that answers my concerns here (although let me know if I'm missing anything). Closing as I think #73 tracks this fine.
