### ISSUE TITLE
Questions on package fallbacks behaviours for connection issues

### ISSUE THREAD

**Issue by guybedford** [domenic/import-maps#58]
I'm just thinking practically about the package fallbacks.

For avoiding connection issues I would likely want my package fallbacks to check say 2 different CDN sources.

Now consider two packages:

```json
{
  "packages": {
    "a": ["https://cdn1/a.js", "https://cdn2/a.js"],
    "b": ["https://cdn2/b.js", "https://cdn2/b.js"],
  }
}
```

For this scenario the following questions come to mind:

1. **Are we then repeating the CDN URLs for each and every package?** This seems redundant but could be ok, although perhaps there could be a way to do this through "path_prefix" rather. That may hinder sharing this technique with polyfills though.
2. Say "a" is requested, and "cdn1" is unavailable, so that the browser has now established a connection to cdn2. **Will the request for "b" still try to create a connection to "cdn1" again?** That is, are we ensuring maximal connection sharing in this process? This should probably be something that is specified into package maps carefully if this scenario is being catered to.

**Comment by domenic** [comment]
1. No. Once the module map is established to a particular URL, the mapping is forever.

2. Yes. This does not operate on a level that knows about connections, only URLs. I don't think there's a realistic way around that.

**Comment by guybedford** [comment]
> Yes. (Assuming you typo'ed and didn't mean to type cdn2 twice for "b".) This does not operate on a level that knows about connections, only URLs. I don't think there's a realistic way around that.

(yes that was a typo thanks) This does worry me a little, since it seems in conflict with the primary use case of having a fallback CDN. 

Consider if we had 100 packages mapped, with each package having a `["https://cdn1/[x].js", "https://cdn2/[x].js"]`. If every resolution is going to have to try to reconnect to CDN1 before resolving CDN2, that seems like it will be a very slow fallback. I'm not sure how connection pooling of failures works at this level, but this seems important to tackle and clarify if such a use case is to be made first-class.
