### ISSUE TITLE
Include path_suffix

### ISSUE THREAD

**Issue by ryanwhite04** [domenic/import-maps#59]
I'm using this to build browser compatible modules by converting bare import specifiers to [UNPKG](https://unpkg.com) URLs.

For **unpkg**, because package name maps or module import maps aren't supported in browsers yet, unpkg will rewrite any bare import specifiers to full urls if the url of the module requested is suffixed with "?module", so my current package name map is as follows

```{
    "path_prefix": "https://unpkg.com/",
    "packages": {
        "@polymer/lit-element": "@0.6.2/lit-element.js?module",
        "ace-builds": "@1.4.1/src-noconflict/ace.js?module",
        "ace-builds/src-noconflict/ext-language_tools.js": "@1.4.1/src-noconflict/ext-language_tools.js?module",
        "ace-builds/src-noconflict/snippets/snippets.js": "@1.4.1/src-noconflict/snippets/snippets.js?module",
        "dedent": "@0.7.0/dist/dedent.js?module"
    }
}
```
which works, but means I have to include paths like "ace-builds/src-noconflict/ext-language_tools.js" explicitly, so it would be nice if I could use 

```
{
    "path_prefix": "https://unpkg.com/",
    "path_suffix": "?module",
    "packages": {
        "@polymer/lit-element": "@0.6.2/lit-element.js",
        "ace-builds": "@1.4.1/src-noconflict/ace.js",
        "dedent": "@0.7.0/dist/dedent.js"
    }
}
```
which would also work with any other path within any of those packages without having to be explicitly declared, but this could be a pointless feature since when this is working in browsers, packages imported from unpkg.com won't need ?module as a suffix anymore anyway.

**Comment by domenic** [comment]
I don't think we should add a solution for this kind of transitional issue to the platform. Your use case is probably better off served with a proxy server, e.g. one that allows you to use normal URLs instead of needing the `?module` suffix. So, let me close this.
