### ISSUE TITLE
If/then/else mappings for feature testing

### ISSUE THREAD

**Issue by littledan** [domenic/import-maps#61]
Continuing from [user story (F)](https://github.com/drufball/layered-apis/issues/34#issuecomment-427599908), it might be a bit suboptimal to have to use a top-level `await` to handle a case where you're testing for the existence of one module and want to take one of two paths depending on that (where it's not a simple fallback for the other module). Maybe we could provide a kind of if/then/else syntax to handle this case, which we could think of as the "desugared" form for the array pattern:

```
{
  "modules": {
    "globalize/list-format": {
      "if": "import:@std/intl-list-format",
      "then": "/node_modules/globalize/list-format-based-on-intl.mjs"
      "else": "/node_modules/globalize/list-format-from-scratch-with-data.mjs"
    }
  }
}
```

(We could decide this case isn't so important, but at TPAC, someone else raised the same issue as I had previously, and we began the discussion with Domenic explaining why depending on top-level await for fallback is not good for performance.)

**Comment by littledan** [comment]
- I don't understand how `then` would conflict--the keys of that object would never be used for anything besides the if/then/else pattern. Anyway, the above was just a straw-person and we could do it in some other way.
- Let's stay away from jumping into JS here, for reasons explained in the README.

**Comment by WebReflection** [comment]
* I guess my point is that resolving `then` module would look confusing with that proposal around
 * I don't think the README mention `if` conditional anywhere, and I wasn't advocating for JS anywhere but in there. The conditional import is otherwise somehow complicated when it comes to features detection due inability to have non-async imports. It'd be cool to solve that case, if possible.

**Comment by littledan** [comment]
How should dynamic JS-generated maps create a conditional over which built-in modules are supported? By the time they are dynamically imported by a script, won't the realm be closed to adding import maps?

**Comment by guybedford** [comment]
I think just supporting conditional fallback arrays already caters to this
use case ok.

**Comment by littledan** [comment]
Fallbacks may work for Layered APIs that can be polyfilled, but if built-in modules are used for new web capabilities, you may want to perform feature detection to decide between different program paths. This was simple with globals, and it could be an unfortunate regression if you needed a jump through top-level await to get this fallback (when avoiding that top-level await is a goal of this proposal's fallback feature). Some hypothetical examples, if some existing browser APIs were done as built-in modules:
- Say IndexedDB were introduced as a built-in module. If it's not present in the browser, use a different codepath based on localStorage.
- Install a ServiceWorker if the browser supports it, or otherwise don't bother. (Might be unnecessary to do synchronously?)
- When loading globalize.js, use Intl if it's there, otherwise load custom data (could be worked around by writing a globalize-to-Intl shim, but the need for this shim is not present currently)

Maybe none of these are completely killer applications, and could be worked around with the right kind of shim, or could be OK with a try/catch around a dynamic import, but it still seems like a regression in usability compared to checking for the presence of globals.

**Comment by dcleao** [comment]
These use cases so much remind me of AMD loader plugins (you know `my/plugin!argument`) which are able to participate in the loading phase. I wonder _what_, if anything, in web standards will ever fill this gap in functionality, which such conciseness and expressiveness.

It will be possible to use top-level awaits for things like this, but accessibility (and possibly performance) would require a solution more seemingly integrated with the module system.

In other threads, ideas like this have been proposed: https://github.com/w3c/webcomponents/issues/645#issuecomment-310811695. I personally love this proposal.

A loader/import plugin implements logic which is is hidden, packaged.
On the contrary, in the fallback conditions here proposed, or in TLA, the logic is _ad hoc_, written case by case — it's gluing logic. So these end up being related but not identical use cases.

@guybedford, @jrburke How do you imagine that AMD/SystemJS loader plugins will be ported to web standard technologies?

**Comment by guybedford** [comment]
@littledan of the cases you mention, the most tricky thing seems to be having the ability to run async code on one of these fallback paths, as far as I can tell? This is actually one of the strong reasons I'm a proponent of top-level await here too as I think it fills an important gap on these workflows too, that can be highly performant if done correctly.

**Comment by domenic** [comment]
It does seem like @littledan may have misinterpreted my words at TPAC. I don't think top-level await is a bad idea for complex cases like the ones in this post. I just think that it should not have to be what people reach for in the simplest cases like polyfills.

**Comment by dcleao** [comment]
@guybedford, @jrburke: ping. Please see my above comment. Thanks.

**Comment by jrburke** [comment]
@dcleao loader plugins might be possible if : is reserved as a special separator in module strings, with `std:` claimed by the JS engine, but other things before the colon would be treated as a userland module to be loaded to then resolve loading for the part after the colon.

It would be worthwhile to figure out and it would allow for more complex logic for determining what to load, but that would require a separate spec from this repo to work out the loader plugin api.

For this specific issue, I am in the camp of not wanting to encode `if` logic as strings.

**Comment by littledan** [comment]
@dcleao @jrburke The explainer is already pretty clear about why it's not feasible to run JavaScript logic in this path, even if it would be useful.

**Comment by jrburke** [comment]
@littledan if you are referring to not using JS in relation to a general [programmable resolution hook](https://github.com/domenic/import-maps#a-programmable-resolution-hook), that is not what I was outlining.

If there is a need for "if" logic, then I feel that is better handled by a different mechanism than strings in import maps. One possibility could be a loader plugin spec for the JS module system.

Hand waving to follow, just for illustrative purposes:

With loader plugins, the resolution could just be done once, for the given module ID, not something that is run for every module resolution in the system.

Taking the example from the start of the thread, there could be a loader plugin module that the `globalize` package provides, call it `globalize/resolve`.

Then modules would ask for `globalize/resolve:list-format`, and the JS module system would have a way for `global/resolve` to tie in to the load sequence to optionally handle resolution, maybe even define the actual export. It would also be able to query for the availability of a module ID, like `@std/intl-list-format`, and decide what to do for resolution. I would expect that resolution only needs to run once for the `globalize/resolve:list-format` ID.

I am not following this repo or the discussions much, so I don't plan to add more swirl to it. I just wanted to try to clarify a bit. But please ignore if this is not clear, we do not have to keep talking about it.
