### ISSUE TITLE
Algorithm for handling chained and circular mappings

### ISSUE THREAD

**Issue by littledan** [domenic/import-maps#64]
How should a chained mapping like `{ "imports": { "/a": "/b", "/b": "/c" } }` behave? Does `import:/a` resolve to `/b` or `/c`? At least for merged maps, it could make sense for them to be composed and resolve to `/c`. But this could lead to some complexity.

What should happen in the case of a circularity, like `{ "imports": { "/a": "/b", "/b": "/a" } }` ? Maintain a list of already-visited things (sounds expensive)? Fail when resolving an import after 20 iterations, like redirects?

I see there's some logic to make the self-resolutions work, in the examples in the README, but I'm not sure exactly what that logic should be (just a one-off for that case?).

**Comment by domenic** [comment]
The current intention is to keep things simple, and have the right hand side only allow non-`import:` URLs (designated as either absolute http(s) URLs, or by starting with `./`, `../`, or `/`), or built-in modules. `import:` URLs are not allowed on the right hand side, and so recursion shouldn't occur.

I _think_ this is consistent with the readme examples, but I admit things may have gotten lost as I shifted my thinking around.

**Comment by littledan** [comment]
I see, thanks for explaining. I can believe this is consistent with the readme examples. If I think of a way to make this clearer in the README, I'll make a PR.

**Comment by littledan** [comment]
To be clear, one consequence is that, if you have an imported module on the right-hand side, you're always referring the original one?

**Comment by domenic** [comment]
I'm not sure what you mean by "imported module on the right-hand side", but if you have a URL there, you're referring to whatever is fetched from that URL.

**Comment by littledan** [comment]
OK, this makes sense (I meant to say "built-in module", but either way, the meaning is clear).
