### ISSUE TITLE
Does import-maps apply to external import()?

### ISSUE THREAD

**Issue by bigopon** [domenic/import-maps#68]
For the following example:

```html
<script src="https://example.com/script.js"></script>
<!-- content of https://example.com/script.js -->
<script>
function loadStuff(path) {
  return import(path).then(m => process(m))
}
</script>
```
And in my JS, what happens if I have this map:
```html
<script type="packagemap">
{
  "path_prefix": "/foo",
  "packages": {
     "moment": { "main": "src/moment.js" },
  }
}
</script>
```
and I do this
```js
loadStuff('moment')
```

**Comment by domenic** [comment]
I don't really understand this example. It appears to be based on the old proposal. It has a confusing HTML file which contains an external script, a comment, and an inline script. But then it has a second HTML file with a packagemap. And then a third file, this time a JavaScript one, with a single line.

Could you write the example using the current proposal, and clearly using a single code block per file?

**Comment by bigopon** [comment]
Sure, sorry for the confusion.
Assume the following is the content of `script.js` at `https://example.com`:
```js
function loadStuff(path) {
  return import(path).then(m => process(m))
}
```
In my page, if I have the following html
```html
<script type="packagemap">
{
  "path_prefix": "/foo",
  "packages": {
     "moment": { "main": "src/moment.js" },
  }
}
</script>
<script src="https://example.com/script.js"></script>
```

What will happen when I do:
```js
loadStuff('moment');
```

**Comment by domenic** [comment]
You will load `/node_modules/moment/src/moment.js`.

**Comment by bigopon** [comment]
@domenic Thanks for the clarification.

**Comment by domenic** [comment]
Do you see a way we could make this clearer in the README?

**Comment by bigopon** [comment]
tbh, I was lazy, so I'll give the README a proper look and get back to you if I have any feedback
 about what's not clear.

**Comment by bigopon** [comment]
I should clarify why I asked first.

I've only known `import()` behavior matching `require()` recently, which is like this, for the above usage without `import-maps`:
```js
loadStuff('./moment.js');
```
Would actually be `import('https://example.com/moment.js')`

So I'm not sure how `import-maps` will alter this behavior, hence the question.

**Comment by domenic** [comment]
Right, one of the purposes of import maps is to make it so that `import()`, or `import`, work even in cases that don't start with `./`, `../`, or `/`. Currently only values with those prefixes work in browsers.

**Comment by bigopon** [comment]
For me, it was mostly about the origin of `import()` statement to resolve URL for relative imports that concerned me. But not having to prefix with those relative URL indicators is also nice.
