### ISSUE TITLE
suggestion: use null to indicate a denied mapping

### ISSUE THREAD

**Issue by allenwb** [domenic/import-maps#69]
> Question: should we introduce a module, e.g. @std/thrower, which just throws an exception? The difference would be in cases like import "@std/async-local-storage", where you wouldn't get an exception with @std/blank because you're not asking for any imports. This is pretty edge-casey.

Since a map is a JSON object, `null` is a syntactically valid value.  So, use `null` instead of @std/blank (or @std/thrower, etc) to indicate a denied mapping:  

```
{
  "imports": {
    "@std/async-local-storage": null
  }
}
```
From a human factors perspective, this seems like a much stronger signal than an arbitrarily assigned built-in name syntactically valid name.

**Comment by domenic** [comment]
What do you think of #66, using an empty array instead? It seems more elegant, but perhaps too clever?

I think empty array should probably work anyway, so then it's a question as to whether we make `null` sugar for the empty array.

**Comment by ljharb** [comment]
Maybe an empty array should be blank (no import names) but `null` should be an exception (no module), as if it was a default argument that required it to be an array?

**Comment by domenic** [comment]
I don't think that makes much sense. An empty array means "this maps to no URLs", i.e. "this has no mapping", i.e. "this module doesn't resolve".

**Comment by ljharb** [comment]
Fair enough. However an empty array might be a bug - in the code that generates the import map, perhaps - whereas null seems intentional. Allowing both or either would make sense to me tho.

**Comment by allenwb** [comment]
> What do you think of #66, using an empty array instead? It seems more elegant, but perhaps too clever?

I think `null` meaning "no mapping" is pedagogically and cognitively simpler. There is a natural progression of understanding from   "a mapping expressed as name : path" to "if a name has no mapping set the path to `null`" to "if there are multiple possible mappings set the path to an array of paths".

Both human and mechanical readers of maps are likely to process `null` and `[` differently. One immediately says there is no way to resolve this mapping.  The other says, time to drill down another lever to determine the mapping.

> I think empty array should probably work anyway, so then it's a question as to whether we make null sugar for the empty array.

You do have to assign some meaning to an empty array. I would reverse the rationale.  An empty array is processed as if it was `null`.

In practice I might use them differently.  Write `null` when I'm intentional about blocking resolution of a name. Write `[ ]` as a placeholder for something I know I will need but haven't worked out yet. My module map linter might issue a warning for `[]`.

**Comment by domenic** [comment]
> You do have to assign some meaning to an empty array. I would reverse the rationale. An empty array is processed as if it was null.

That doesn't make sense to me. The right hand side of the mapping is always an array listing the possible locations to resolve to. We have a sugar syntax for the one-location case where `"single string"` gets translated into `["single string"]`, and we could have a sugar syntax for the zero-location case where `null` gets translated to `[]`, but the foundation is an array of zero or more locations.

Anyway, I take your point that `null` may be easier to read, so we're just quibbling around the pedagogy, not the outcome.
