### ISSUE TITLE
Terminology

### ISSUE THREAD

**Issue by domenic** [domenic/import-maps#74]
Consider the following example:

```json
{
  "imports": {
    "foo1": "./bar",
    "foo2": "https://bar.com/",
    "foo3": "@std/bar",
    "foo4": ["./bar"],
    "foo5": [],
    "foo6/": "https://bar.com/6/"
  },
  "scopes": {
    "/scope1": { ... },
    "/scope2": { ... }
  }
}
```

To write a good spec, and have a sensible ecosystem that has intelligible conversations, we need terms for various things here.

So far I have:

- **Import map**: the whole thing
- **Specifier map**: the whole `{ "foo1": ... }` structure. Also the `{ ... }`s after `"/scope1":` and `"/scope2":` (they have the same schema)
- **Specifier key**: `"foo1"` ... `"foo5"` and `"foo6/"` are specifier keys
  - **Simple specifier key**: `"foo1" ... `"foo5"` are simple specifier keys
  - **Prefix specifier key**: `"foo6/"` is a prefix specifier key
- **Map target string** (or, [below proposal: "address"](https://github.com/domenic/import-maps/issues/74#issuecomment-436666198)): `"./bar"`, `"https://bar.com/"`, `"@std/bar"`, and `"https://bar.com/6/"` are all map target strings
  - `"./bar"` is a **relative URL-like map target string**
  - `"https://bar.com/"` and `"https://bar.com/6/"` are **absolute URL map target strings**
  - `"@std/bar"` is a **built-in module map target string**
- **Map target array**: `["./bar"]` and `[]` are map target arrays
- **Scope prefix**: `"/scope1"` and `"/scope2"` are scope prefixes.

I'm not a big fan of my choices so far, so better suggestions are welcome. But I'd like to pick something soon so I don't have to rename everything later.

Conditions for closing this issue: be happy with a final set of names; make sure the tests/reference implementation reflect them; make sure spec.md does not contradict them; make sure README.md reflects them (perhaps informally).

**Comment by robpalme** [comment]
If the "imports" map is better referred to as the "specifier map", would
renaming it "specifiers" make conversations easier?

**Comment by domenic** [comment]
I don't think we should change the UI to match the terms; rather we should change the terms to match the UI.

**Comment by mkay581** [comment]
cool, I like the "specifier" term because its already used in package managers like npm I believe. Although I've seen what we're calling "specifier keys" here be referenced in npm as "fields" sometimes. 

seems like "import map" in this sense is a pretty loaded term, though. Because its not just an `imports` map in your example but also a  `scopes` map".

If there was no terminology, I'd just call the "whole thing" an object with `imports` and `scopes` maps. Which doesn't seem confusing so I'm wondering if you really need a definitive term for the "whole thing". Don't think package managers have a term for something on this level either (i.e. npm just calls the "whole thing" a package.json I believe)

**Comment by mkay581** [comment]
oh okay. I guess I didn't know what you meant by "whole thing". I thought you just meant the actual instance of code, rather than the name of the feature/spec. Thanks for the clarification.

**Comment by matthewp** [comment]
I've always thought of __specifier__ to mean the thing written in the source. So __specifier map__ makes sense, as does __specifier key__ (although I think shortening to __specifier__ works too).

The one that I'm hung up on is __map target string__.  It seems they are all URLs with the exception of things like `@std/bar`. It would be great if we could call it __target URL__.  What about __address__, is that too vague?
