### ISSUE TITLE
Using 'active script' for determining `import:` URL scope is brittle

### ISSUE THREAD

**Issue by bicknellr** [domenic/import-maps#77]
(relevant text: https://github.com/domenic/import-maps/blob/e4dd5e3b070ca5bd56bf65bfa01085045207a52c/spec.md#modifications-to-the-url-parser-for-import-urls)

Using 'active script' to determine the scope for a particular `import:` URL seems to break down easily when passing URLs from scripts in one scope to scripts in another:
    
`./lib.js`, in scope A:
```js
export makeImage = url => {
  const image = document.createElement('img');
  image.src = url;
  return src;
}
```

`./caller.js`, in scope B:
```js
import {makeImage} from "lib/lib.js";
document.body.appendChild(makeImage("import:somewhere/image.png"));
```

If `caller.js` and `lib.js` are in separate scopes, but the deciding factor for which scope applies to a particular `import:` URL is based on the 'active script' at the time the `import:` URL string would be consumed for resolution, then `import:somewhere/image.png` would be resolved in scope A, used by `lib.js`, rather than scope B. How can a caller one scope provide an `import:` URL to another scope that resolves to the network URL expected by the caller?

I think this would require some kind of URL resolution function ("`import.resolve`") but doing so seems to be currently precluded by other problems ([CORS](https://github.com/domenic/import-maps/issues/76), [async](https://github.com/domenic/import-maps/issues/18)).

**Comment by domenic** [comment]
This seems like a dupe of #75, do you agree?

**Comment by bicknellr** [comment]
Yup, this is a dupe.
