### ISSUE TITLE
Import maps merging behaviors

### ISSUE THREAD

**Issue by guybedford** [domenic/import-maps#88]
When loading multiple import maps, what merging behavior should there be?

* Can a package be redefined or does it throw when the same package is defined by another map?
* I would assume scopes always merge?

Also worth noting that if `package` is defined in one map, `package/` could still be defined in another map and vice versa? Would we want to restrict this too?

**Comment by blittle** [comment]
The example here does have `lodash` getting overridden by a second map: https://github.com/domenic/import-maps#dynamic-import-map-example

**Comment by domenic** [comment]
This is the current proposal: https://github.com/domenic/import-maps/blob/master/spec.md#merging-import-maps

**Comment by guybedford** [comment]
Thanks - it seems like these are defined then, great to know.
