### ISSUE TITLE
Consider: default extensions

### ISSUE THREAD

**Issue by MicahZoltu** [domenic/import-maps#89]
When writing TypeScript, one may write something like:
```typescript
import { Apple } from './apple'
```
This will compile into ES2018 without any changes.  Unfortunately, `./apple` won't exist on the server, but `./apple.js` will.  One _can_ include the `.js` extension in the import statement and TypeScript will "do the right thing", but that is a bit of a hack as the code is really saying "load a module named apple as resolved by the module loader" which may have a `.js` suffix in one environment (like the browser) but may have a different suffix in other environments (like TSC which will look for `.d.ts` or `.ts`).

While I don't think that the browser should just "guess", I would like to be able to tell the browser how to resolve modules that don't have a suffix in one try.  Perhaps something along the lines of
```json
{
  "default-extension": ".js",
  "packages": {
    ...
  }
}
```
I haven't fully grokked yet how relative path imports work (it sounds like this is in flux and unclear to everyone) but however they are resolved it would be nice if I could tell the system "if you run into a module without an extension, add `.js` to it.

**Comment by daKmoR** [comment]
actually, it seems the alignment is more to go with always providing file extensions.

At least that's how it's in the browser and how it will become for node => see details here
http://2ality.com/2018/12/nodejs-esm-phases.html#simplifying-module-specifiers

**Comment by domenic** [comment]
Yeah, the proposal requires you to always provide file extensions. If you want to create an individual import map entry for each file, e.g. `"/x/y" -> "x/y.js"`, then you can, but you'll have to put in the extra work. The default path encourages you to be explicit.

**Comment by jkrems** [comment]
It would most likely be on Typescript to translate (or even append) file extensions when a project is compiled. That might be an interesting issue for the TypeScript tracker. :)

**Comment by Pauan** [comment]
See https://github.com/Microsoft/TypeScript/issues/16577

**Comment by justinfagnani** [comment]
TypeScript already works just fine. It doesn't change the import specifier, but import `apple.js` and it'll know to look at `apple.ts`for types.
