### ISSUE TITLE
Possible trailing slash confusion

### ISSUE THREAD

**Issue by guybedford** [domenic/import-maps#93]
If I create the following map:

```json
{
  "imports": {
    "x/": "y"
  }
}
```

then `import('x/asdf')` will resolve in the reference implementation to `/asdf` instead of `/y/asdf`.

This is because the trailing `/` is necessary on `y` for it to resolve correctly as the parent address URL in https://github.com/domenic/import-maps/blob/master/reference-implementation/lib/resolver.js#L26.

It could be worth adding a check either at parse time or at resolution time to ensure that any map specifier key ending with `/` also has its target address ending with `/`.

It may not seem like a big thing, but this sort of usability can improve the experience I think.

I can put together a PR on the above if it sounds sensible as well.

**Comment by domenic** [comment]
Fascinating, I would have expected at least `"yasdf"`. Per https://github.com/domenic/import-maps/issues/91#issuecomment-453591013, I agree that at least for now the right thing to do is require all target addresses to end in `/`, and throw out any that don't.

(Throw out vs. throw error: see #80. Let's throw them out for now for consistency, but per that issue we should give a warning, and I'm still open to being argued into fail-hard.)

A PR sounds lovely.

**Comment by guybedford** [comment]
Happy to "throw out", but I hope we can make the warnings first-class and not an afterthought here, otherwise it does seem like a worse-off experience than just breaking or throwing.

**Comment by domenic** [comment]
Yeah, we start putting those warnings into the reference implementation. Maybe just `console.warn`, which gets mocked during tests?

**Comment by guybedford** [comment]
Ok I can aim to put a simple approach together.
